name: reload-feeds

on:
  # Runs at 08:00 UTC everyday
  schedule:
    - cron: '00 08 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
  
      - name: Check change
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          pip install -r requirements.txt
          python main.py
          git commit -am "update feed" || true
          git push
